language: node_js
node_js:
  - '12'

cache:
  yarn: true

install:
  - yarn install

script:
  - yarn build esm -t -s
  - yarn docs:build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc-dist/
  github_token: $GITHUB_TOKEN
  keep_history: false
  name: xuguo
  email: xg501@outlook.com
  on:
    tags: true
